# Generated by Django 5.1.4 on 2024-12-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAuto', models.CharField(max_length=100, null=True, verbose_name='Название автомобиля')),
                ('descriptionAuto', models.TextField(max_length=255, null=True, verbose_name='Описание автомобиля')),
                ('priceAuto', models.CharField(max_length=7, null=True, verbose_name='Начало курсов')),
                ('image', models.ImageField(null=True, upload_to='static/img/cars/', verbose_name='Картинка атомобиля')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
