# Generated by Django 5.1.4 on 2024-12-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobApp', '0004_cars_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='image',
            new_name='imageAuto',
        ),
    ]
