# Generated by Django 5.1.4 on 2024-12-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobApp', '0005_rename_image_cars_imageauto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={},
        ),
        migrations.RemoveField(
            model_name='cars',
            name='priceAuto',
        ),
        migrations.AlterField(
            model_name='cars',
            name='descriptionAuto',
            field=models.TextField(default='пока нет описания для данной модели'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='nameAuto',
            field=models.CharField(default='наименование', max_length=255),
            preserve_default=False,
        ),
    ]
