# Generated by Django 5.1.4 on 2024-12-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobApp', '0006_alter_cars_options_remove_cars_priceauto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='imageAuto',
            field=models.ImageField(null=True, upload_to='cars/', verbose_name='Картинка атомобиля'),
        ),
    ]
